language: node_js

node_js: node

before_install:
  - npm install yarn -g

cache:
  directories:
  - $HOME/.yarn-cache

install:
  - yarn --prefer-offline

after_success:
  - bash <(curl -s https://codecov.io/bash)
