module.exports = {
  // backend created
  INSTALL_ENDED: 'INSTALL_ENDED',
  INSTALL_FAILED: 'INSTALL_FAILED',
  INSTALL_STARTED: 'INSTALL_STARTED',
  INSTALL_CANCELLED: 'INSTALL_CANCELLED',
  DOWNLOAD_STARTED: 'DOWNLOAD_STARTED',
  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
  DOWNLOAD_ENDED: 'DOWNLOAD_ENDED',
  DOWNLOAD_CANCELLED: 'DOWNLOAD_CANCELLED',
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  LOAD_EXPERIMENTS: 'LOAD_EXPERIMENTS',
  LOADING_EXPERIMENTS: 'LOADING_EXPERIMENTS',
  EXPERIMENTS_LOADED: 'EXPERIMENTS_LOADED',
  EXPERIMENTS_LOAD_ERROR: 'EXPERIMENTS_LOAD_ERROR',
  EXPERIMENT_ENABLED: 'EXPERIMENT_ENABLED',
  EXPERIMENT_DISABLED: 'EXPERIMENT_DISABLED',
  EXPERIMENT_UNINSTALLING: 'EXPERIMENT_UNINSTALLING',
  EXPERIMENT_UNINSTALLED: 'EXPERIMENT_UNINSTALLED',
  // frontend created
  SHOW_EXPERIMENT: 'SHOW_EXPERIMENT',
  CHANGE_PANEL_HEIGHT: 'CHANGE_PANEL_HEIGHT',
  GET_EXPERIMENTS: 'GET_EXPERIMENTS',
  // webapp created
  INSTALL_EXPERIMENT: 'INSTALL_EXPERIMENT',
  UNINSTALL_EXPERIMENT: 'UNINSTALL_EXPERIMENT',
  UNINSTALL_SELF: 'UNINSTALL_SELF',
  SYNC_INSTALLED: 'SYNC_INSTALLED'
}
